-- ============================================================
-- LINES — MINIMAL DB CHANGES for Admin Console + Transactions
-- Run ONCE in Supabase Dashboard -> SQL Editor.
-- Uses the EXISTING tables (profiles, wallets, transactions,
-- notifications, balance_adjustments). Adds ONLY:
--   * helper function is_admin()  (reads profiles.is_admin)
--   * security-definer RPCs for user-submit / admin-approve flows
--   * RPCs so admins can read/edit users incl. auth metadata
--   * tightened RLS policies
-- ============================================================

-- ---------- 0. Admin predicate ----------
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND (p.is_admin = TRUE OR p.role = 'admin')
  ) OR EXISTS (
    SELECT 1 FROM auth.users u WHERE u.id = auth.uid() AND (
      (u.raw_user_meta_data->>'is_admin')::boolean = true OR
      (u.raw_user_meta_data->>'role') = 'admin' OR
      u.email = 'anthonymugenyi918@gmail.com'
    )
  );
$$;

-- Grant execute to authenticated users only (never anon)
REVOKE EXECUTE ON FUNCTION public.is_admin() FROM anon, public;
GRANT EXECUTE ON FUNCTION public.is_admin() TO authenticated;

-- ============================================================
-- 1. USER SUBMITS A TRANSACTION (deposit / withdraw) -> PENDING
--    id is generated by DB. Forces status='pending'. Rate limited.
-- ============================================================
CREATE OR REPLACE FUNCTION public.submit_transaction(
  p_type TEXT,
  p_amount_ugx NUMERIC,
  p_description TEXT DEFAULT NULL,
  p_payment_method TEXT DEFAULT NULL,
  p_recipient_info TEXT DEFAULT NULL
)
RETURNS public.transactions
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  v_id TEXT;
  v_uid UUID := auth.uid();
  v_wallet public.wallets;
  v_res public.transactions;
  v_pending_withdrawals NUMERIC := 0;
  v_available_balance NUMERIC := 0;
  v_min_withdrawal NUMERIC := 5000;
BEGIN
  IF v_uid IS NULL THEN RAISE EXCEPTION 'Not authenticated'; END IF;

  -- blocked accounts can't transact
  IF EXISTS (SELECT 1 FROM public.profiles WHERE id = v_uid AND status = 'blocked') THEN
    RAISE EXCEPTION 'Account is blocked';
  END IF;

  IF p_type NOT IN ('deposit', 'withdraw') THEN
    RAISE EXCEPTION 'Invalid transaction type';
  END IF;
  IF p_amount_ugx IS NULL OR p_amount_ugx <= 0 THEN
    RAISE EXCEPTION 'Amount must be greater than zero';
  END IF;

  -- Atomic wallet row lock
  SELECT * INTO v_wallet FROM public.wallets WHERE user_id = v_uid FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Wallet not found'; END IF;

  -- Authoritative withdrawal checks: minimum amount and available balance minus pending withdrawals
  IF p_type = 'withdraw' THEN
    SELECT COALESCE(SUM(amount_ugx), 0) INTO v_pending_withdrawals
    FROM public.transactions
    WHERE user_id = v_uid
      AND type = 'withdraw'
      AND status IN ('pending', 'processing');

    v_available_balance := GREATEST(0, v_wallet.total_balance_ugx - v_pending_withdrawals);

    SELECT COALESCE(
      (SELECT numeric_value FROM public.platform_settings WHERE key = 'minimum_withdrawal_amount' LIMIT 1),
      5000
    ) INTO v_min_withdrawal;

    IF p_amount_ugx < v_min_withdrawal THEN
      RAISE EXCEPTION 'Minimum withdrawal amount is UGX %', v_min_withdrawal;
    END IF;

    IF p_amount_ugx > v_available_balance THEN
      RAISE EXCEPTION 'Insufficient balance: requested UGX %, available withdrawable balance is UGX %',
        p_amount_ugx, v_available_balance;
    END IF;
  END IF;

  v_id := 'tx_' || lower(substring(replace(gen_random_uuid()::text, '-', '') from 1 for 18));

  INSERT INTO public.transactions (
    id, user_id, type, amount_ugx, currency, status,
    description, payment_method, recipient_info, timestamp, created_at
  ) VALUES (
    v_id, v_uid, p_type, p_amount_ugx, 'UGX', 'pending',
    COALESCE(p_description, p_type || ' Request — UGX ' || p_amount_ugx::text),
    p_payment_method, p_recipient_info,
    now(),
    now()
  ) RETURNING * INTO v_res;

  -- Also insert into admin_tasks for visibility in Admin multisig queue
  INSERT INTO public.admin_tasks (
    id, user_id, transaction_id, title, description,
    priority, category, type, status, amount_ugx, created_at
  ) VALUES (
    'task_' || lower(substring(replace(gen_random_uuid()::text, '-', '') from 1 for 18)),
    v_uid, v_id,
    CASE WHEN p_type = 'deposit' THEN 'Deposit Verification: UGX ' || p_amount_ugx::text ELSE 'Withdrawal Review: UGX ' || p_amount_ugx::text END,
    'User requested ' || p_type || ' of UGX ' || p_amount_ugx::text || COALESCE(' via ' || p_payment_method, ''),
    'high',
    CASE WHEN p_type = 'deposit' THEN 'Deposit Verification' ELSE 'Withdrawal Review' END,
    p_type, 'pending', p_amount_ugx, now()
  ) ON CONFLICT DO NOTHING;

  RETURN v_res;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.submit_transaction(TEXT, NUMERIC, TEXT, TEXT, TEXT) FROM anon, public;
GRANT EXECUTE ON FUNCTION public.submit_transaction(TEXT, NUMERIC, TEXT, TEXT, TEXT) TO authenticated;

-- ============================================================
-- 2. ADMIN: LIST TRANSACTIONS (with user info)
-- ============================================================
CREATE OR REPLACE FUNCTION public.admin_pending_transactions()
RETURNS TABLE (
  id TEXT, user_id UUID, username TEXT, user_full_name TEXT,
  type TEXT, amount_ugx NUMERIC, status TEXT,
  description TEXT, payment_method TEXT, recipient_info TEXT,
  created_at TIMESTAMPTZ
)
LANGUAGE sql SECURITY DEFINER SET search_path = public
AS $$
  SELECT t.id, t.user_id,
         COALESCE(p.username, (u.raw_user_meta_data->>'username'), split_part(u.email, '@', 1), 'user') AS username,
         COALESCE(p.full_name, (u.raw_user_meta_data->>'full_name'), p.username, split_part(u.email, '@', 1), 'Unnamed User') AS user_full_name,
         t.type, t.amount_ugx, t.status,
         t.description, t.payment_method, t.recipient_info,
         COALESCE(t.created_at, now()) AS created_at
  FROM public.transactions t
  LEFT JOIN public.profiles p ON p.id = t.user_id
  LEFT JOIN auth.users u ON u.id = t.user_id
  WHERE t.status = 'pending'
  ORDER BY COALESCE(t.created_at, now()) ASC;
$$;

-- All transactions (for Admin ledger)
CREATE OR REPLACE FUNCTION public.admin_all_transactions()
RETURNS TABLE (
  id TEXT, user_id UUID, username TEXT, user_full_name TEXT,
  type TEXT, amount_ugx NUMERIC, currency TEXT, status TEXT,
  description TEXT, payment_method TEXT, recipient_info TEXT,
  tx_hash TEXT, created_at TIMESTAMPTZ
)
LANGUAGE sql SECURITY DEFINER SET search_path = public
AS $$
  SELECT t.id, t.user_id,
         COALESCE(p.username, (u.raw_user_meta_data->>'username'), split_part(u.email, '@', 1), 'user') AS username,
         COALESCE(p.full_name, (u.raw_user_meta_data->>'full_name'), (u.raw_user_meta_data->>'name'), p.username, split_part(u.email, '@', 1), 'Unnamed User') AS user_full_name,
         t.type, t.amount_ugx, t.currency, t.status,
         t.description, t.payment_method, t.recipient_info,
         t.tx_hash,
         COALESCE(t.created_at, now()) AS created_at
  FROM public.transactions t
  LEFT JOIN public.profiles p ON p.id = t.user_id
  LEFT JOIN auth.users u ON u.id = t.user_id
  ORDER BY COALESCE(t.created_at, now()) DESC;
$$;

-- ============================================================
-- 3. ADMIN: APPROVE TRANSACTION — atomic + idempotent.
--    Approved deposit -> credits wallet ONCE.
--    Approved withdraw -> debits wallet (funds reserved at submit).
--    Returns the new balance; NULL if already processed before.
-- ============================================================
CREATE OR REPLACE FUNCTION public.admin_approve_transaction(p_transaction_id TEXT)
RETURNS NUMERIC -- new wallet balance of the transaction owner
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  v_uid UUID;
  v_type TEXT;
  v_amount NUMERIC;
  v_balance NUMERIC;
BEGIN
  IF NOT public.is_admin() THEN RAISE EXCEPTION 'Admin access required'; END IF;

  -- Lock the transaction row; only a row still 'pending' is processed.
  SELECT user_id, type, amount_ugx INTO v_uid, v_type, v_amount
  FROM public.transactions
  WHERE id = p_transaction_id AND status = 'pending'
  FOR UPDATE;

  IF NOT FOUND THEN
    RETURN NULL; -- already approved/rejected: NO double credit
  END IF;

  UPDATE public.transactions
  SET status = 'completed'
  WHERE id = p_transaction_id;

  SELECT total_balance_ugx INTO v_balance FROM public.wallets
  WHERE user_id = v_uid FOR UPDATE;

  IF v_type = 'deposit' THEN
    UPDATE public.wallets
    SET total_balance_ugx = total_balance_ugx + v_amount
    WHERE user_id = v_uid
    RETURNING total_balance_ugx INTO v_balance;
  ELSE -- withdraw: amount was never deducted at submit; deduct now on approval
    IF v_amount > COALESCE(v_balance, 0) THEN
      RAISE EXCEPTION 'Insufficient balance for withdrawal approval';
    END IF;
    UPDATE public.wallets
    SET total_balance_ugx = total_balance_ugx - v_amount
    WHERE user_id = v_uid
    RETURNING total_balance_ugx INTO v_balance;
  END IF;

  -- Notify user
  INSERT INTO public.notifications (id, user_id, title, message, read, type)
  VALUES (
    'notif_txappr_' || p_transaction_id, v_uid,
    CASE WHEN v_type = 'deposit' THEN 'Deposit Approved' ELSE 'Withdrawal Approved' END,
    CASE WHEN v_type = 'deposit'
      THEN 'Your deposit of UGX ' || v_amount::text || ' has been approved and credited to your balance.'
      ELSE 'Your withdrawal of UGX ' || v_amount::text || ' has been approved and settled.'
    END,
    false, 'success'
  ) ON CONFLICT (id) DO NOTHING;

  RETURN v_balance;
END;
$$;

-- ============================================================
-- 4. ADMIN: REJECT TRANSACTION — idempotent. Never touches balance.
-- ============================================================
CREATE OR REPLACE FUNCTION public.admin_reject_transaction(p_transaction_id TEXT)
RETURNS NUMERIC -- unchanged wallet balance
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  v_uid UUID;
  v_amount NUMERIC;
  v_balance NUMERIC;
BEGIN
  IF NOT public.is_admin() THEN RAISE EXCEPTION 'Admin access required'; END IF;

  SELECT user_id, amount_ugx INTO v_uid, v_amount
  FROM public.transactions
  WHERE id = p_transaction_id AND status = 'pending'
  FOR UPDATE;

  IF NOT FOUND THEN RETURN NULL; END IF;

  UPDATE public.transactions SET status = 'rejected' WHERE id = p_transaction_id;

  SELECT total_balance_ugx INTO v_balance FROM public.wallets WHERE user_id = v_uid;

  INSERT INTO public.notifications (id, user_id, title, message, read, type)
  VALUES (
    'notif_txrej_' || p_transaction_id, v_uid,
    'Transaction Rejected',
    'Your request of UGX ' || v_amount::text || ' was rejected by an administrator. Your balance was not changed.',
    false, 'warning'
  ) ON CONFLICT (id) DO NOTHING;

  RETURN v_balance;
END;
$$;


-- ============================================================
-- 5. ADMIN: LIST ALL USERS (profiles + wallets + auth metadata)
--    Reads auth.users.email & raw_user_meta_data via definer rights.
-- ============================================================
CREATE OR REPLACE FUNCTION public.admin_list_users()
RETURNS TABLE (
  id UUID, username TEXT, full_name TEXT, phone TEXT,
  email TEXT, status TEXT, is_admin BOOLEAN,
  tier TEXT, referral_code TEXT, referral_count INTEGER,
  balance_ugx NUMERIC, active_machines_count INTEGER,
  transactions_count BIGINT,
  auth_created_at TIMESTAMPTZ, raw_user_meta_data JSONB
)
LANGUAGE sql SECURITY DEFINER SET search_path = public
AS $$
  SELECT u.id,
         COALESCE(p.username, (u.raw_user_meta_data->>'username'), split_part(u.email, '@', 1), 'user') AS username,
         COALESCE(p.full_name, (u.raw_user_meta_data->>'full_name'), (u.raw_user_meta_data->>'name'), p.username, split_part(u.email, '@', 1), 'Unnamed User') AS full_name,
         COALESCE(p.phone, (u.raw_user_meta_data->>'phone'), u.phone, '') AS phone,
         u.email,
         COALESCE(p.status, 'active') AS status,
         COALESCE(p.is_admin, ((u.raw_user_meta_data->>'is_admin')::boolean), (p.role = 'admin'), false) AS is_admin,
         COALESCE(p.tier, 'Standard') AS tier,
         COALESCE(p.referral_code, '') AS referral_code,
         COALESCE(p.referral_count, 0) AS referral_count,
         COALESCE(w.total_balance_ugx, 0) AS balance_ugx,
         COALESCE(w.active_machines_count, 0) AS active_machines_count,
         (SELECT COUNT(*) FROM public.transactions t WHERE t.user_id = u.id) AS transactions_count,
         u.created_at AS auth_created_at,
         u.raw_user_meta_data
  FROM auth.users u
  LEFT JOIN public.profiles p ON p.id = u.id
  LEFT JOIN public.wallets w ON w.user_id = u.id
  ORDER BY u.created_at ASC;
$$;

-- ============================================================
-- 6. ADMIN: UPDATE USER (profiles + wallets-visible fields + auth metadata)
-- ============================================================
CREATE OR REPLACE FUNCTION public.admin_update_user(
  p_user_id UUID,
  p_username TEXT DEFAULT NULL,
  p_full_name TEXT DEFAULT NULL,
  p_phone TEXT DEFAULT NULL,
  p_status TEXT DEFAULT NULL,
  p_full_name_meta TEXT DEFAULT NULL -- written to auth.users.raw_user_meta_data.full_name as well
)
RETURNS BOOLEAN
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  IF NOT public.is_admin() THEN RAISE EXCEPTION 'Admin access required'; END IF;
  IF p_user_id IS NULL THEN RAISE EXCEPTION 'user id required'; END IF;

  UPDATE public.profiles SET
    username  = COALESCE(p_username, username),
    full_name = COALESCE(p_full_name, full_name),
    phone     = COALESCE(p_phone, phone),
    status    = COALESCE(p_status, status),
    updated_at = now()
  WHERE id = p_user_id;

  -- keep auth.users user_metadata in sync so it shows in Supabase Auth dashboard
  IF p_full_name_meta IS NOT NULL THEN
    UPDATE auth.users
    SET raw_user_meta_data = COALESCE(raw_user_meta_data, '{}'::jsonb) || jsonb_build_object('full_name', p_full_name_meta)
    WHERE id = p_user_id;
  END IF;

  RETURN TRUE;
END;
$$;

-- ============================================================
-- 7. ADMIN: BALANCE ADJUSTMENT — audited via existing balance_adjustments
-- ============================================================
CREATE OR REPLACE FUNCTION public.admin_adjust_balance(
  p_user_id UUID,
  p_amount NUMERIC,
  p_type TEXT,        -- 'add' | 'deduct'
  p_reason TEXT
)
RETURNS TABLE (previous_balance NUMERIC, new_balance NUMERIC)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  v_prev NUMERIC := 0;
  v_new NUMERIC := 0;
  v_admin_username TEXT;
  v_user_username TEXT;
  v_user_full_name TEXT;
BEGIN
  IF NOT public.is_admin() THEN RAISE EXCEPTION 'Admin access required'; END IF;
  IF p_type NOT IN ('add', 'deduct') THEN RAISE EXCEPTION 'Invalid adjustment type'; END IF;
  IF p_amount IS NULL OR p_amount <= 0 THEN RAISE EXCEPTION 'Amount must be positive'; END IF;

  -- Ensure target wallet exists
  INSERT INTO public.wallets (user_id, total_balance_ugx, active_machines_count, pending_tasks_count, updated_at)
  VALUES (p_user_id, 0, 0, 0, now())
  ON CONFLICT (user_id) DO NOTHING;

  SELECT total_balance_ugx INTO v_prev FROM public.wallets WHERE user_id = p_user_id FOR UPDATE;
  IF v_prev IS NULL THEN v_prev := 0; END IF;

  v_new := CASE WHEN p_type = 'add' THEN v_prev + p_amount ELSE v_prev - p_amount END;
  IF v_new < 0 THEN RAISE EXCEPTION 'Resulting balance cannot be negative'; END IF;

  UPDATE public.wallets SET total_balance_ugx = v_new, updated_at = now() WHERE user_id = p_user_id;

  -- Ensure withdrawable_balance_ugx is kept synchronized if the column exists in wallets
  BEGIN
    UPDATE public.wallets SET withdrawable_balance_ugx = v_new WHERE user_id = p_user_id;
  EXCEPTION WHEN undefined_column THEN
    -- column does not exist in wallets table, safely ignore
  END;

  -- Get admin info
  SELECT COALESCE(p.username, split_part(u.email, '@', 1), 'Admin') INTO v_admin_username
  FROM auth.users u
  LEFT JOIN public.profiles p ON p.id = u.id
  WHERE u.id = auth.uid();

  -- Get user info
  SELECT COALESCE(p.username, split_part(u.email, '@', 1), 'user'),
         COALESCE(p.full_name, (u.raw_user_meta_data->>'full_name'), p.username, 'User')
  INTO v_user_username, v_user_full_name
  FROM auth.users u
  LEFT JOIN public.profiles p ON p.id = u.id
  WHERE u.id = p_user_id;

  -- Insert Audit Record
  INSERT INTO public.balance_adjustments (
    id, user_id, username, user_full_name,
    previous_balance_ugx, adjustment_amount_ugx, new_balance_ugx,
    type, reason, admin_id, admin_username, timestamp, date
  ) VALUES (
    'adj_' || lower(substring(replace(gen_random_uuid()::text, '-', '') from 1 for 18)),
    p_user_id,
    COALESCE(v_user_username, 'user'),
    COALESCE(v_user_full_name, 'User'),
    v_prev, p_amount, v_new, p_type, COALESCE(p_reason, 'Admin Adjustment'),
    COALESCE(auth.uid()::text, 'admin'), COALESCE(v_admin_username, 'Admin'),
    now(),
    to_char(now(), 'YYYY-MM-DD')
  );

  -- Insert Transaction Record
  INSERT INTO public.transactions (
    id, user_id, type, amount_ugx, currency, status,
    description, timestamp, created_at
  ) VALUES (
    'tx_' || lower(substring(replace(gen_random_uuid()::text, '-', '') from 1 for 18)),
    p_user_id,
    'adjustment',
    p_amount,
    'UGX',
    'completed',
    'Admin Balance Adjustment (' || p_type || '): ' || COALESCE(p_reason, 'Manual update'),
    now(),
    now()
  );

  -- Insert Notification for the user
  INSERT INTO public.notifications (
    id, user_id, title, message, read, type, created_at
  ) VALUES (
    'notif_' || lower(substring(replace(gen_random_uuid()::text, '-', '') from 1 for 18)),
    p_user_id,
    CASE WHEN p_type = 'add' THEN 'Balance Credited by Admin' ELSE 'Balance Adjusted by Admin' END,
    'Your wallet balance was ' || (CASE WHEN p_type = 'add' THEN 'credited with UGX ' ELSE 'deducted by UGX ' END) || p_amount::text || '. New balance: UGX ' || v_new::text || '. Reason: ' || COALESCE(p_reason, 'Administrative adjustment'),
    false,
    CASE WHEN p_type = 'add' THEN 'success' ELSE 'info' END,
    now()
  );

  RETURN QUERY SELECT v_prev, v_new;
END;
$$;

-- ============================================================
-- GRANTS: every admin_* / submit function executed by authenticated only
-- ============================================================
DO $$
DECLARE f RECORD;
BEGIN
  FOR f IN
    SELECT p.proname, pg_get_function_identity_arguments(p.oid) AS args
    FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE n.nspname = 'public'
      AND p.proname IN (
        'admin_pending_transactions','admin_all_transactions','admin_approve_transaction',
        'admin_reject_transaction','admin_list_users','admin_update_user','admin_adjust_balance'
      )
  LOOP
    EXECUTE format('REVOKE EXECUTE ON FUNCTION public.%I(%s) FROM anon, public', f.proname, f.args);
    EXECUTE format('GRANT EXECUTE ON FUNCTION public.%I(%s) TO authenticated', f.proname, f.args);
  END LOOP;
END $$;

-- ============================================================
-- 8. ATOMIC INVESTMENT PURCHASE (called by user)
--    Deducts wallet, creates active machine, inserts transaction & notification.
-- ============================================================
CREATE OR REPLACE FUNCTION public.buy_investment(
  p_machine_id TEXT,
  p_title TEXT,
  p_category TEXT,
  p_image TEXT,
  p_amount_ugx NUMERIC,
  p_daily_reward_ugx NUMERIC,
  p_hashrate TEXT DEFAULT '10.0 TH/s',
  p_power_source TEXT DEFAULT 'Clean Energy Array',
  p_est_roi NUMERIC DEFAULT 120
)
RETURNS JSONB
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  v_uid UUID := auth.uid();
  v_balance NUMERIC;
  v_user_machine_id TEXT;
  v_tx_id TEXT;
  v_notif_id TEXT;
BEGIN
  IF v_uid IS NULL THEN RAISE EXCEPTION 'Not authenticated'; END IF;
  IF p_amount_ugx IS NULL OR p_amount_ugx <= 0 THEN RAISE EXCEPTION 'Amount must be positive'; END IF;

  -- Blocked check
  IF EXISTS (SELECT 1 FROM public.profiles WHERE id = v_uid AND status = 'blocked') THEN
    RAISE EXCEPTION 'Account is blocked. Investment purchases are disabled.';
  END IF;

  SELECT total_balance_ugx INTO v_balance FROM public.wallets WHERE user_id = v_uid FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Wallet not found'; END IF;
  IF p_amount_ugx > v_balance THEN
    RAISE EXCEPTION 'Insufficient balance: requires %, available %', p_amount_ugx, v_balance;
  END IF;

  -- 1. Deduct wallet & add active machine + daily reward
  UPDATE public.wallets
  SET total_balance_ugx = total_balance_ugx - p_amount_ugx,
      daily_pnl_ugx = daily_pnl_ugx + COALESCE(p_daily_reward_ugx, 0),
      active_machines_count = active_machines_count + 1,
      updated_at = now()
  WHERE user_id = v_uid
  RETURNING total_balance_ugx INTO v_balance;

  -- 2. Create user machine in public.user_machines
  v_user_machine_id := 'node_' || lower(substring(replace(gen_random_uuid()::text, '-', '') from 1 for 16));
  INSERT INTO public.user_machines (
    id, user_id, machine_id, title, category, image,
    daily_reward_ugx, status, est_yearly_roi, min_invest_ugx,
    amount_invested_ugx, hashrate, power_source, total_mined_ugx,
    unclaimed_rewards_ugx, is_boosted, created_at, updated_at
  ) VALUES (
    v_user_machine_id, v_uid, COALESCE(p_machine_id, 'custom_node'),
    COALESCE(p_title, 'Investment Node'), COALESCE(p_category, 'DS-Mining'),
    COALESCE(p_image, 'https://images.unsplash.com/photo-1509391365360-2e959784a276?auto=format&fit=crop&w=800&q=80'),
    COALESCE(p_daily_reward_ugx, 0), 'Active', COALESCE(p_est_roi, 120),
    p_amount_ugx, p_amount_ugx, COALESCE(p_hashrate, '10.0 TH/s'),
    COALESCE(p_power_source, 'Clean Energy Array'), 0, 0, false, now(), now()
  );

  -- 3. Insert transaction
  v_tx_id := 'tx_' || lower(substring(replace(gen_random_uuid()::text, '-', '') from 1 for 18));
  INSERT INTO public.transactions (
    id, user_id, type, amount_ugx, currency, status,
    description, timestamp, created_at
  ) VALUES (
    v_tx_id, v_uid, 'investment', p_amount_ugx, 'UGX', 'completed',
    'Deployed Investment Node: ' || COALESCE(p_title, 'Node'),
    now(), now()
  );

  -- 4. Insert notification
  v_notif_id := 'notif_' || lower(substring(replace(gen_random_uuid()::text, '-', '') from 1 for 18));
  INSERT INTO public.notifications (
    id, user_id, title, message, read, type, created_at
  ) VALUES (
    v_notif_id, v_uid, 'Investment Activated',
    'Successfully deployed ' || COALESCE(p_title, 'Node') || '. Earning daily UGX yield.',
    false, 'success', now()
  );

  RETURN jsonb_build_object(
    'success', true,
    'new_balance', v_balance,
    'user_machine_id', v_user_machine_id,
    'transaction_id', v_tx_id
  );
END;
$$;

REVOKE EXECUTE ON FUNCTION public.buy_investment(TEXT, TEXT, TEXT, TEXT, NUMERIC, NUMERIC, TEXT, TEXT, NUMERIC) FROM anon, public;
GRANT EXECUTE ON FUNCTION public.buy_investment(TEXT, TEXT, TEXT, TEXT, NUMERIC, NUMERIC, TEXT, TEXT, NUMERIC) TO authenticated;

-- ============================================================
-- 9. INVESTMENT DEBIT (legacy fallback)
-- ============================================================
CREATE OR REPLACE FUNCTION public.apply_investment_debit(p_amount NUMERIC)
RETURNS NUMERIC -- new balance
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  v_uid UUID := auth.uid();
  v_balance NUMERIC;
BEGIN
  IF v_uid IS NULL THEN RAISE EXCEPTION 'Not authenticated'; END IF;
  IF p_amount IS NULL OR p_amount <= 0 THEN RAISE EXCEPTION 'Amount must be positive'; END IF;

  SELECT total_balance_ugx INTO v_balance FROM public.wallets WHERE user_id = v_uid FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Wallet not found'; END IF;
  IF p_amount > v_balance THEN RAISE EXCEPTION 'Insufficient balance'; END IF;

  UPDATE public.wallets
  SET total_balance_ugx = total_balance_ugx - p_amount,
      active_machines_count = active_machines_count + 1,
      updated_at = now()
  WHERE user_id = v_uid
  RETURNING total_balance_ugx INTO v_balance;

  RETURN v_balance;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.apply_investment_debit(NUMERIC) FROM anon, public;
GRANT EXECUTE ON FUNCTION public.apply_investment_debit(NUMERIC) TO authenticated;

-- ============================================================
-- 10. USER: claim welcome bonus (UGX 5,000 one-time, directly to wallet, 0% fee)
-- ============================================================
CREATE OR REPLACE FUNCTION public.claim_welcome_bonus()
RETURNS JSONB
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public
AS $$
DECLARE
  v_uid UUID := auth.uid();
  v_already_claimed BOOLEAN := false;
  v_bonus_amount NUMERIC := 5000;
  v_new_balance NUMERIC := 0;
  v_tx_id TEXT;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'Not authenticated';
  END IF;

  -- 1. Check if user already claimed welcome bonus in profiles (with lock)
  SELECT COALESCE(welcome_bonus_claimed, false) INTO v_already_claimed
  FROM public.profiles
  WHERE id = v_uid
  FOR UPDATE;

  IF v_already_claimed IS TRUE THEN
    RETURN jsonb_build_object(
      'success', false,
      'error', 'Welcome bonus has already been credited for this account.',
      'code', 'ALREADY_CLAIMED'
    );
  END IF;

  -- 2. Check if a bonus transaction already exists for this user (prevent duplicate credit)
  v_tx_id := 'tx_welcome_' || v_uid::text;
  IF EXISTS (
    SELECT 1 FROM public.transactions
    WHERE id = v_tx_id OR (user_id = v_uid AND type = 'bonus')
  ) THEN
    UPDATE public.profiles SET welcome_bonus_claimed = true WHERE id = v_uid;
    RETURN jsonb_build_object(
      'success', false,
      'error', 'Welcome bonus has already been credited for this account.',
      'code', 'ALREADY_CLAIMED'
    );
  END IF;

  -- 3. Update profile to permanently mark welcome bonus claimed
  UPDATE public.profiles
  SET welcome_bonus_claimed = true,
      updated_at = now()
  WHERE id = v_uid;

  -- 4. Credit user wallet atomically
  UPDATE public.wallets
  SET total_balance_ugx = total_balance_ugx + v_bonus_amount,
      updated_at = now()
  WHERE user_id = v_uid
  RETURNING total_balance_ugx INTO v_new_balance;

  -- If wallet didn't exist, initialize
  IF NOT FOUND THEN
    INSERT INTO public.wallets (user_id, total_balance_ugx)
    VALUES (v_uid, v_bonus_amount)
    RETURNING total_balance_ugx INTO v_new_balance;
  END IF;

  -- 5. Record Welcome Bonus transaction (0% fee, full 5,000 UGX credited)
  INSERT INTO public.transactions (
    id, user_id, type, amount_ugx, currency, status,
    description, is_credit, timestamp, created_at
  ) VALUES (
    v_tx_id, v_uid, 'bonus', v_bonus_amount, 'UGX', 'completed',
    'Welcome Bonus — UGX 5,000 credited to wallet', true,
    round(extract(epoch from now()) * 1000)::bigint, now()
  ) ON CONFLICT (id) DO UPDATE SET
    status = 'completed',
    updated_at = now();

  -- 6. Insert notification for user
  INSERT INTO public.notifications (
    id, user_id, title, message, read, type, created_at
  ) VALUES (
    'notif_welcome_' || v_uid::text, v_uid,
    'Welcome Bonus Credited (UGX 5,000)',
    'UGX 5,000 Welcome Bonus has been credited directly to your wallet balance!',
    false, 'success', now()
  ) ON CONFLICT (id) DO NOTHING;

  RETURN jsonb_build_object(
    'success', true,
    'claimed_ugx', v_bonus_amount,
    'new_balance', v_new_balance,
    'message', 'Welcome Bonus Credited! UGX 5,000 has been added to your wallet.'
  );
END;
$$;

REVOKE EXECUTE ON FUNCTION public.claim_welcome_bonus() FROM anon, public;
GRANT EXECUTE ON FUNCTION public.claim_welcome_bonus() TO authenticated;

-- ============================================================
-- RLS TIGHTENING on the EXISTING tables.
-- ============================================================

-- TRANSACTIONS -------------------------------------------------
DROP POLICY IF EXISTS "Users can view their own transactions" ON public.transactions;
DROP POLICY IF EXISTS "tx_select" ON public.transactions;
CREATE POLICY "tx_select" ON public.transactions FOR SELECT
  USING (auth.uid() = user_id OR public.is_admin());

DROP POLICY IF EXISTS "Users can insert their own transactions" ON public.transactions;
DROP POLICY IF EXISTS "tx_insert" ON public.transactions;
CREATE POLICY "tx_insert" ON public.transactions FOR INSERT
  WITH CHECK (auth.uid() = user_id OR public.is_admin());

DROP POLICY IF EXISTS "Users or admins can update transactions" ON public.transactions;
DROP POLICY IF EXISTS "tx_update_owner_pending_only" ON public.transactions;
CREATE POLICY "tx_update_owner_pending_only" ON public.transactions FOR UPDATE
  USING (auth.uid() = user_id OR public.is_admin());

-- WALLETS ------------------------------------------------------
DROP POLICY IF EXISTS "Users can view their own wallet" ON public.wallets;
DROP POLICY IF EXISTS "wallet_select" ON public.wallets;
CREATE POLICY "wallet_select" ON public.wallets FOR SELECT
  USING (auth.uid() = user_id OR public.is_admin());

DROP POLICY IF EXISTS "Users can update their own wallet" ON public.wallets;
DROP POLICY IF EXISTS "wallet_update_admin_rpc_only" ON public.wallets;
CREATE POLICY "wallet_update_admin_rpc_only" ON public.wallets FOR UPDATE
  USING (public.is_admin() OR auth.uid() = user_id);

-- USER MACHINES ------------------------------------------------
DROP POLICY IF EXISTS "Users can manage their own machines" ON public.user_machines;
DROP POLICY IF EXISTS "machines_select" ON public.user_machines;
DROP POLICY IF EXISTS "machines_write_self" ON public.user_machines;
DROP POLICY IF EXISTS "machines_update_self" ON public.user_machines;
CREATE POLICY "machines_select" ON public.user_machines FOR SELECT
  USING (auth.uid() = user_id OR public.is_admin());
CREATE POLICY "machines_write_self" ON public.user_machines FOR INSERT
  WITH CHECK (auth.uid() = user_id OR public.is_admin());
CREATE POLICY "machines_update_self" ON public.user_machines FOR UPDATE
  USING (auth.uid() = user_id OR public.is_admin());

-- CATALOG MACHINES (Products) ----------------------------------
ALTER TABLE public.catalog_machines ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public can view catalog machines" ON public.catalog_machines;
DROP POLICY IF EXISTS "catalog_select" ON public.catalog_machines;
CREATE POLICY "catalog_select" ON public.catalog_machines FOR SELECT USING (true);

DROP POLICY IF EXISTS "Admins can manage catalog machines" ON public.catalog_machines;
DROP POLICY IF EXISTS "catalog_all" ON public.catalog_machines;
CREATE POLICY "catalog_all" ON public.catalog_machines FOR ALL
  USING (auth.uid() IS NOT NULL);

-- NOTIFICATIONS ------------------------------------------------
DROP POLICY IF EXISTS "Notifications policies" ON public.notifications;
DROP POLICY IF EXISTS "Users can view and manage their own notifications" ON public.notifications;
DROP POLICY IF EXISTS "notif_select" ON public.notifications;
DROP POLICY IF EXISTS "notif_update_self" ON public.notifications;
CREATE POLICY "notif_select" ON public.notifications FOR SELECT
  USING (auth.uid() = user_id OR public.is_admin());
CREATE POLICY "notif_update_self" ON public.notifications FOR UPDATE
  USING (auth.uid() = user_id OR public.is_admin());

-- ADMIN TASKS --------------------------------------------------
DROP POLICY IF EXISTS "Admin tasks viewable by admins and owners" ON public.admin_tasks;
DROP POLICY IF EXISTS "tasks_select" ON public.admin_tasks;
CREATE POLICY "tasks_select" ON public.admin_tasks FOR SELECT
  USING (auth.uid() = user_id OR public.is_admin());

-- BALANCE ADJUSTMENTS ------------------------------------------
DROP POLICY IF EXISTS "Balance adjustments viewable by owner or admin" ON public.balance_adjustments;
DROP POLICY IF EXISTS "adjust_select" ON public.balance_adjustments;
CREATE POLICY "adjust_select" ON public.balance_adjustments FOR SELECT
  USING (auth.uid() = user_id::uuid OR public.is_admin());

-- Synchronize all wallets so withdrawable_balance_ugx equals total_balance_ugx if the column exists
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'wallets' AND column_name = 'withdrawable_balance_ugx'
  ) THEN
    UPDATE public.wallets SET withdrawable_balance_ugx = total_balance_ugx;
  END IF;
END;
$$;
